version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: